baseURL = "https://dnduykhoa.github.io/my-blog"
languageCode = "vi"
title = "Blog Lập Trình"
theme = "hugo-profile"

relativeURLs = false
canonifyURLs = true
enableGitInfo = false

# CHỈ KHAI BÁO OUTPUTS MỘT LẦN Ở ĐÂY
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

[params]
  title = "Blog Lập Trình Java & JavaScript"
  description = "Chia sẻ kiến thức về lập trình web"
  dateFormat = "02/01/2006"
  UseBootstrapCDN = true

  staticPath = "/my-blog"

  [params.datesFormat]
    article = "02/01/2006"
    articleList = "02/01/2006"

  [params.author]
    name = "Đào Nguyễn Duy Khoa"

  [params.hero]
    enable = true
    intro = "Xin chào, mình là"
    title = "Đào Nguyễn Duy Khoa"
    subtitle = "Sinh viên ngành CNTT - HUTECH"
    content = "Đam mê phát triển web và chia sẻ kiến thức"
    image = "/images/avatar.jpeg"

  [params.navbar]
    enable = true
    showSearch = false
    showToggle = false
    showRSS = false
    alignment = "center"
    searchDisplay = false
    brandDisplay = true
    brandalignment = "left"

  [params.search]
    enable = false
    type = "hidden"
    placeholder = ""
    clearButton = false

  [params.blog]
    enable = true
    showDate = true
    showTags = true
    showAuthor = true
    authorImage = true
    showRecentPosts = true
    recentPostsLimit = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
[markup.goldmark.parser]
  attribute = true

# Menu: khai báo trực tiếp các array-of-tables ở cấp top-level
[[menu.main]]
  name = "Trang chủ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Bài viết"
  url = "/blogs"
  weight = 2

[[menu.main]]
  name = "Giới Thiệu"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Liên Hệ"
  url = "/contact"
  weight = 4
  